config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :incomes

  devise_for :users
  resources :comments
  get 'pages/info'
  resources :ideas


  get 'dashboard', to: 'dashboards#index'
  root to: redirect('/dashboard')

  resources :categories do 
    # resources :expense_categories, controller: :expense_categories, type: 'Expense'
    # resources :income_categories, controller: :income_categories, type: 'Income'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :category
  belongs_to :user
    validates :title, presence: true
end

app/controllers/incomes_controller.rb
class IncomesController < BaseController
  layout 'master'
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all.page(params[:page]).per(10)
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
    @currentUser = current_user.id
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    byebug
    @income = Income.new(income_params)
    
    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def income_params
      params.require(:income).permit(:title, :description, :quantity, :amount, :user_id, :income_category_id)
    end
end
  

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<%= form_with(model: income, local: true) do |form| %>
 

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>
  <div class="field">
  <%= form.label :Amount %>
  <%= form.number_field :amount ,step: :any %>
  </div>
  <div class="field">
    <%= form.label :income_category_id %>
    <%= form.collection_select :income_category_id, IncomeCategory.all, :id, :title %>
  </div>
  <%= form.hidden_field :user_id, value: @currentUser %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form', income: @income %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-header">

    <h3 class="card-title">Income</h3>
  <span style="float:right"><%= link_to 'Add Income', new_income_path %></span>

  </div>
  <!-- /.card-header -->
  <div class="card-body p-0">
    <table class="table table-striped">
      <thead>
        <tr>
          <th style="width: 10px">SN</th>
          <th>Title</th>
          <th>Type</th>
        </tr>
      </thead>
      <tbody>
    
        <% @count = 0 %>
        <% @incomes.each do |income| %>
        <tr>
          <td><%= income.title %></td>
          <td><%= income.description %></td>
          <td><%= income.category_id %></td>
          <td><%= link_to 'Show', income %></td>
          <td><%= link_to 'Edit', edit_income_path(income) %></td>
          <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>

    </table>  
  <%= paginate @incomes %>


  </div>

</div>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form', income: @income %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @income.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @income.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @income.category_id %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>