config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :incomes

  devise_for :users
  resources :comments
  get 'pages/info'
  resources :ideas


  get 'dashboard', to: 'dashboards#index'
  root to: redirect('/dashboard')

  resources :categories do 
    # resources :expense_categories, controller: :expense_categories, type: 'Expense'
    # resources :income_categories, controller: :income_categories, type: 'Income'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :expenses
    has_many :incomes
     
    scope :income_categories, ->{where type: 'Income'}
    scope :expense_categories, ->{where type: 'Expense'}
    validates :title, :type, presence: true
  
end

app/controllers/categories_controller.rb
class CategoriesController < BaseController
  layout 'master'
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.page(params[:page]).per(10)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
  
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
     
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      if(params[:category])
      params.require(:category).permit(:title, :type)
      elsif(params[:expense_category])
      params.require(:expense_category).permit(:title, :type)
      else
        params.require(:income_category).permit(:title, :type)

      end
      
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card card-warning">
  <div class="card-header">
    <h3 class="card-title">Quick Example</h3>
  </div>
  <!-- /.card-header -->
  <!-- form start -->
  <form role="form">
    <div class="card-body">
      <div class="form-group">
        <label for="exampleInputEmail1">Title</label>
        <%= form.text_field :title ,class:"form-control" %>
      </div>
      
      
      <div class="form-check">
        <%= form.select :type, ["ExpenseCategory","IncomeCategory"],class:"form-control"%>
      </div>
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
    
    <%= form.submit %>

    </div>
  </form>
</div>
<!-- /.card -->

app/views/categories/edit.html.erb
<h1>Editing Category</h1>
<%= form_for(@category, url: category_path(@category), local: true) do |form| %>

<%= render 'form', category: @category, form: form %>
<% end %>

<%= link_to 'Show', category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-header">

    <h3 class="card-title">Category</h3>
  <span style="float:right"><%= link_to 'Add Category', new_category_path %></span>

  </div>
  <!-- /.card-header -->
  <div class="card-body p-0">
    <table class="table table-striped">
      <thead>
        <tr>
          <th style="width: 10px">#</th>
          <th>Title</th>
          <th>Type</th>
        </tr>
      </thead>
      <tbody>
    
      <% @count = 0 %>
      <% @categories.each do |category| %>
        <tr>
          <td><%= @count += 1 %> </td>
          <td><%= category.title%></td>
          
          
          <td><span class="badge bg-danger"><%= category.type %></span></td>
          <td><%= link_to 'Show', category_path(category) %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
 
        </tr>
        
        <%end %>
      </tbody>
    </table>
    <%= paginate @categories %>

  </div>
  <!-- /.card-body -->
</div>
<!-- /.card -->

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= form_for(@category, url: categories_path(@category), local: true) do |form| %>

<%= render 'form', category: @category, form: form%>

<% end %>
<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>